version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
  - dependency-name: karma
    versions:
    - 6.3.1
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
  - dependency-name: sinon-chai
    versions:
    - 3.6.0
  - dependency-name: diagram-js
    versions:
    - 7.2.3
  - dependency-name: min-dash
    versions:
    - 3.7.0
  - dependency-name: chai
    versions:
    - 4.3.4
